### ISSUE TITLE
stopped at "waiting for ssh"

### ISSUE THREAD

**Issue by akatukiyou** [rainpole/packer-vsphere#11]
See below message, my build stopped at "ssh", it wont go any further.

```
==> vsphere-iso.linux-<sensitive>-server: IP address: 10.30.7.109
==> vsphere-iso.linux-<sensitive>-server: Using SSH communicator to connect: 10.30.7.109
==> vsphere-iso.linux-<sensitive>-server: Waiting for SSH to become available...
```

By any chance if there is way to see more information for debugging?

**Comment by tenthirtyam** [comment]
Assuming the default configuration of the examples included in the repo, SSH should be enabled on the Linux-based machine image as it starts the build and receives an IP address. You may wish to confirm that SSH to the target network is allowed by your firewalls as a first step.

**Comment by akatukiyou** [comment]
I clone the repo again and only changed info for connecting to our vCenter, it sitll stopped at "waiting for ssh to become available", i dont know if the issue is "ssh services not up and running " or the credentials are not right. is there  detailed information I can check? That subnet has no restriction on any traffic.

**Comment by tenthirtyam** [comment]
Hello.

Please fill out the issue template and provide more detail on the linux distribution selected, any changes to the `.pkr.hcl`, scripts or config files, and redacted `.hcl` variables.

in the meantime, verify that once the image is online if you can directly SSH via user/pass to the machine image - which you should be able to do even if auth_keys are enabled. You can use the VM console to login directly and ensure the user/pass is accurate and that ssh services are running.

Without additional detail I will not know if it’s something from within the repository examples, environmental, or related to Packer or the linux distribution.

Ryan

**Comment by akatukiyou** [comment]
ok, done as requested. see details in bug report
