### ISSUE TITLE
CPU <> Sockets

### ISSUE THREAD

**Issue by jbpoint** [rainpole/packer-vsphere#12]
I am trying to configure the vsphere template that i have for example 4 CPUs. 
![image](https://user-images.githubusercontent.com/87362739/125601020-b1f900f4-94bf-4c70-8130-fdfaf92b10e0.png)

Can you advice?

**Comment by tenthirtyam** [comment]
Hi!

These settings are in the .hcl configurations.

vm_cpu_sockets = 2
vm_cpu_cores   = 1

Ryan
