### ISSUE TITLE
Add support for Rocky Linux

### ISSUE THREAD

**Issue by alexanderek** [rainpole/packer-vsphere#13]
Hello

Could you add [Rocky Linux](https://rockylinux.org) support please?

**Comment by tenthirtyam** [comment]
I'll take this into consideration for my next round of updates and examples.

**Comment by tenthirtyam** [comment]
[Background](https://www.theregister.com/AMP/2021/07/09/centos_stream_greg_kurtzer/) on creation of [Rocky Linux Project](https://rockylinux.org) based on the deprecation of CentOS Linux and transition to [CentOS Stream](https://www.centos.org/centos-stream/).

**Comment by tenthirtyam** [comment]
Please note that Guest OS Customization is currently **[not supported](https://partnerweb.vmware.com/programs/guestOS/guest-os-customization-matrix.pdf)** for Rocky Linux as of vCenter Server 7.0 Update 2.

**Comment by tenthirtyam** [comment]
Enhancement for supporting Rocky Linux Server 8 [committed.](https://github.com/rainpole/packer-vsphere/commit/4ba6e786a441d1824b71afa05ec0a98135cbe60e)
