### ISSUE TITLE
SSH settings in ubuntu "user data" file

### ISSUE THREAD

**Issue by akatukiyou** [rainpole/packer-vsphere#14]
The current settings for ssh in [user data] file for ubuntu is below 

`ssh:
    install-server: true
    authorized-keys:
      - ecdsa-sha2-nistp521 .............
    allow-pw: true`

according to [doc ](https://ubuntu.com/server/docs/install/autoinstall-reference#ssh)here

`allow-pw` should set to `false` if `authorized-key` is in use.

Please verify

**Comment by tenthirtyam** [comment]
Would need to test that this does not impact the Packer build as it uses SSH user/pass for executing the machine image build.

Please use the issue template and provide additional detail for scenario and any results of testing with this set to false.

Ryan

**Comment by tenthirtyam** [comment]
Based on my testing, changing the `user-data` file to specify `allow-pw:false` instead of `allow-pw:true` will result in a build failure that will disconnect Packer during the build process as it will not longer be able to connect with the `build_username` / `build_password.`

A more appropriate solution would be to modify `/scripts/linux/ubuntu-server-cleanup.sh` to modify the `sshd_config `via **sed**.

This section:

```
### Configure SSH for Public Key Authentication. ###
echo '> Configuring SSH for Public Key Authentication ...'
sudo sed -i '/^PermitRootLogin/s/yes/no/' /etc/ssh/sshd_config
sudo sed -i "s/.*PubkeyAuthentication.*/PubkeyAuthentication yes/g" /etc/ssh/sshd_config
```

This would need to have the following additional settings changes _at a minimum_:

```
ChallengeResponseAuthentication no
PasswordAuthentication no
```

This could be done by adding to the  `/scripts/linux/ubuntu-server-cleanup.sh` ...

```
sudo grep -q "ChallengeResponseAuthentication" /etc/ssh/sshd_config && sed -i "/^[^#]*ChallengeResponseAuthentication[[:space:]]yes.*/c\ChallengeResponseAuthentication no" /etc/ssh/sshd_config || echo "ChallengeResponseAuthentication no" >> /etc/ssh/sshd_config
sudo grep -q "^[^#]*PasswordAuthentication" /etc/ssh/sshd_config && sed -i "/^[^#]*PasswordAuthentication[[:space:]]yes/c\PasswordAuthentication no" /etc/ssh/sshd_config || echo "PasswordAuthentication no" >> /etc/ssh/sshd_config
```

We'll mark this for testing.

Ryan

**Comment by tenthirtyam** [comment]
By default, both Public Key Authentication and Password Authentication are enabled for Linux distributons. If you wish to disable Password Authentication and only use Public Key Authentication, comment or remove the portion of the associated script in the `/scripts` directory. Comments are added to the scripts to call out what to uncomment, if desired.

Example:` /scripts/linux/ubuntu-server-cleanup.sh`

```
### Configure SSH for Public Key Authentication. ###
echo '> Configuring SSH for Public Key Authentication ...'
### Comment or r4move the line below to to disable Public Key Authentication allow _only_ Password Authentication. ###
sudo sed -i 's/.*PubkeyAuthentication.*/PubkeyAuthentication yes/' /etc/ssh/sshd_config
### Uncomment the line below to to disable Password Authentication and enforce _only_ Public Key Authentication. ###
### sudo sed -i 's/#PasswordAuthentication.*/PasswordAuthentication no/' /etc/ssh/sshd_config
```

Ryan
