### ISSUE TITLE
Stopped at "Waiting for SSH to become available....

### ISSUE THREAD

**Issue by akatukiyou** [rainpole/packer-vsphere#15]
When filing a bug, please include the following information. 

**Description**
Stopped at "Waiting for SSH to become available.... then times out with error 

"Error waiting for SSH: Packer experienced an authentication error when trying to connect via SSH. This can happen if your username/password are wrong. You may want to double-check your credentials as part of your debugging process. original error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain""

**Steps to Reproduce**

**VMware vSphere Version**

vSphere 7.0.2

**HashiCorp Packer Version**

Packer 1.7.3

**Simplified Packer Build or Variables File(s)**

I only changed the credential in pakvar.hcl to connect to my vCenter, which works fine.
I replaced "authorized-keys" value  in [user data] file and replaced the key in [keys] folder
Nothing else changed, I kept build_username   &  build_password unchanged. 

**Guest Operating System and Environment Details**

Ubuntu 20.04
Environment was untouched from var file

**Log Fragments and crash.log Files**

2021/07/14 23:41:40 packer.exe plugin: [INFO] Attempting SSH connection to 10.10.110.235:22...
2021/07/14 23:41:40 packer.exe plugin: [DEBUG] reconnecting to TCP connection for SSH
2021/07/14 23:41:40 packer.exe plugin: [DEBUG] handshaking with SSH
2021/07/14 23:41:44 packer.exe plugin: [DEBUG] SSH handshake err: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain
2021/07/14 23:41:44 packer.exe plugin: [DEBUG] Detected authentication error. Increasing handshake attempts.
2021/07/14 23:41:51 packer.exe plugin: [INFO] Attempting SSH connection to 10.10.110.235:22...
2021/07/14 23:41:51 packer.exe plugin: [DEBUG] reconnecting to TCP connection for SSH
2021/07/14 23:41:51 packer.exe plugin: [DEBUG] handshaking with SSH
2021/07/14 23:41:53 packer.exe plugin: [DEBUG] SSH handshake err: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain
2021/07/14 23:41:53 packer.exe plugin: [DEBUG] Detected authentication error. Increasing handshake attempts.
2021/07/14 23:42:00 packer.exe plugin: [INFO] Attempting SSH connection to 10.10.110.235:22...
2021/07/14 23:42:00 packer.exe plugin: [DEBUG] reconnecting to TCP connection for SSH
2021/07/14 23:42:00 packer.exe plugin: [DEBUG] handshaking with SSH
2021/07/14 23:42:03 packer.exe plugin: [DEBUG] SSH handshake err: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain
2021/07/14 23:42:03 packer.exe plugin: [DEBUG] Detected authentication error. Increasing handshake attempts.
2021/07/14 23:42:10 packer.exe plugin: [INFO] Attempting SSH connection to 10.10.110.235:22...
2021/07/14 23:42:10 packer.exe plugin: [DEBUG] reconnecting to TCP connection for SSH
2021/07/14 23:42:10 packer.exe plugin: [DEBUG] handshaking with SSH
2021/07/14 23:42:14 packer.exe plugin: [DEBUG] SSH handshake err: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain
2021/07/14 23:42:14 packer.exe plugin: [DEBUG] Detected authentication error. Increasing handshake attempts.
2021/07/14 23:42:14 ui error: ==> vsphere-iso.linux-<sensitive>-server: Error waiting for SSH: Packer experienced an authentication error when trying to connect via SSH. This can happen if your username/password are wrong. You may want to double-check your credentials as part of your debugging process. original error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain
2021/07/14 23:42:14 ui: ask: ==> vsphere-iso.linux-<sensitive>-server: Pausing before cleanup of step 'StepWaitForIp'. Press enter to continue.
2021/07/14 23:42:14 ui: ask: ==> vsphere-iso.linux-<sensitive>-server: Pausing before cleanup of step 'StepBootCommand'. Press enter to continue.
2021/07/14 23:42:20 ui: ask: ==> vsphere-iso.linux-<sensitive>-server: Pausing before cleanup of step 'StepRun'. Press enter to continue.
2021/07/14 23:42:21 ui: ==> vsphere-iso.linux-<sensitive>-server: Power off VM...

**Additional Context**

while waiting for SSH to become available, i can ping the vm, i was trying to ssh into the vm directly by using 

build_username   = "rainpole"
build_password   = "R@in!$aG00dThing."

Access was denied, "You dont have permission to connect"

**Comment by tenthirtyam** [comment]
I'm assuming that the host from which you are running the Packer builds is not the same network on which the  images are being built. Based on the information provided I suspect that the IP is not being reported back or not routable back to the Packer host.

Today, I verified that the examples for Ubuntu work as expected by cloning the repo and only changing the `vsphere.pkrvars.hcl` file with my testbed vSphere settings and by running it on an L3 routable network. (I already das the `.iso` files.)

You can see below that Packer initializes the HTTP server on `http://172.16.11.254:8257/` ...

```
Building a Ubuntu Sever 20.04 LTS Template for VMware vSphere ...
Applying the HashiCorp Packer Build ...
vsphere-iso.linux-ubuntu-server: output will be in this color.
==> vsphere-iso.linux-ubuntu-server: Creating VM...
==> vsphere-iso.linux-ubuntu-server: Customizing hardware...
==> vsphere-iso.linux-ubuntu-server: Adding SATA controller...
==> vsphere-iso.linux-ubuntu-server: Mounting ISO images...
==> vsphere-iso.linux-ubuntu-server: Adding configuration parameters...
==> vsphere-iso.linux-ubuntu-server: Starting HTTP server on port 8257
==> vsphere-iso.linux-ubuntu-server: Set boot order...
==> vsphere-iso.linux-ubuntu-server: Power on VM...
==> vsphere-iso.linux-ubuntu-server: Waiting 5s for boot...
==> vsphere-iso.linux-ubuntu-server: HTTP server is working at http://172.16.11.254:8257/
==> vsphere-iso.linux-ubuntu-server: Typing boot command...
```

And then the machine comes online via DHCP with the IP of `172.16.14.191` ...

```
==> vsphere-iso.linux-ubuntu-server: Waiting for IP...
==> vsphere-iso.linux-ubuntu-server: IP address: 172.16.14.191
==> vsphere-iso.linux-ubuntu-server: Using SSH communicator to connect: 172.16.14.191
==> vsphere-iso.linux-ubuntu-server: Waiting for SSH to become available...
```

And then connects via SSH with the `build_username` and  `build_password` ...
```
==> vsphere-iso.linux-ubuntu-server: Connected to SSH!
==> vsphere-iso.linux-ubuntu-server: Uploading ../../../keys/id_ecdsa.pub => /tmp/id_ecdsa.pub
    vsphere-iso.linux-ubuntu-server: id_ecdsa.pub 269 B / 269 B [==============================================================] 100.00%
```

I recommend ensuring that the host running Packer is accessible from your DHCP range.

Ryan

**Comment by akatukiyou** [comment]
Thanks for your investigation !

Indeed !!! since you posted your log, i noticed your line

`==> vsphere-iso.linux-ubuntu-server: HTTP server is working at http://172.16.11.254:8257/`

compared to my line

`==> vsphere-iso.linux-ubuntu-server: HTTP server is working at http://169.254.103.4:8954/`

**aha !!!   169.254.x.x Automatic Private IP address !!!**

So I made a vm in the targeting subnet and run packer again from the target subnet, HTTP server works in the target network

`==> vsphere-iso.linux-<sensitive>-server: HTTP server is working at http://10.10.110.253:8679/`
`==> vsphere-iso.linux-<sensitive>-server: Typing boot command...`
`==> vsphere-iso.linux-<sensitive>-server: Waiting for IP...`
`==> vsphere-iso.linux-<sensitive>-server: IP address: 10.10.110.242`
`==> vsphere-iso.linux-<sensitive>-server: Using SSH communicator to connect: 10.10.110.242`

Everything start working, Nice work !  

But it brings me another question, why the http server got an auto private ip address? I can't setup a machine in the target subnet each time I run packer.

I couldn't find the doc for how that http server works with packer? do you mind if you can link me a reference? I want to understand that part.

Thanks

**Comment by tenthirtyam** [comment]
I suspect that the system which you are initializing the build on has >1 network interface, of which one is disconnected / not disabled is being selected for binding. 

Unfortunately, I've not had much luck using [http_bind_address](https://www.packer.io/docs/builders/vsphere/vsphere-iso#http_bind_address) or [http_ip](https://www.packer.io/docs/builders/vsphere/vsphere-iso#http_ip) with the `vsphere-iso` Packer provisioner.

Ryan
