### ISSUE TITLE
Almalinux and Windows, Static IP

### ISSUE THREAD

**Issue by jbpoint** [rainpole/packer-vsphere#16]
Hi, 

i tried to create the templates with a static ip, without success. 
Can you help me to create templates (almalinux, windows 2016 and windows 2019) at creation with a static ip?

**Comment by tenthirtyam** [comment]
Hi @jbpoint,

Thanks for filing the issue. I've authored to repository to only support the use of specific Linux distributions and the use of DHCP. 

Could you please two issues using the "**Feature Request**" template.

1. Enhancement: Support for Almalinux
2. Feature: Support for Static Network Address Assignment

Thanks,
Ryan

**Comment by jbpoint** [comment]
Where do i find "Feature Request" template?

**Comment by tenthirtyam** [comment]
**Issues** > **New Issue** > **Feature Request** > **Get Started**.

Use the markdown code included in the template to guide the inputs. You can use the Preview to review before submitting.

Ryan
