### ISSUE TITLE
Option to use static IP assignment during machine image builds.

### ISSUE THREAD

**Issue by jbpoint** [rainpole/packer-vsphere#17]
**Community Note**

**Description:** 

Please add an option in the examples to support static IP addresses during machine image builds.

**Use Case(s):** 

DHCP is not always available within the datacenter environment.

**Potential Configuration:** 

None offered.

**Potential References:**

None offered.

**Comment by tenthirtyam** [comment]
There's not a native method in the [Packer Builder for VMware vSphere](https://www.packer.io/docs/builders/vsphere/vsphere-iso) to use static IP address assignment. Although this has been mentions / requested in [#37](https://github.com/jetbrains-infra/packer-builder-vsphere/issues/37).

Options to enable this include:

### Ubuntu 18.04
Update the ks.cfg preseed file.

```
# Networking
d-i netcfg/disable_autoconfig boolean true

# IPv4 Setup
d-i netcfg/get_ipaddress string <static_ipv4_address>
d-i netcfg/get_netmask string <static_ipv4_netmask>
d-i netcfg/get_gateway string <static_ipv4_gateways>
d-i netcfg/get_nameservers string <static_ipv4_dnsservers>
d-i netcfg/confirm_static boolean true
```

### Ubuntu 20.04 and later
Update the `user-data` used by cloud-init.

```
  network:
    network:
      version: 2
      ethernets:
        ens33:
         addresses: <static_ipv4_address_cidr>
         gateway4: <static_ipv4_gateway>
         nameservers:
           addresses: [<static_ipv4_dnsservers>]

```
### Windows Server
Update the Autounattend.xml with [Ipv4Settings](https://docs.microsoft.com/en-us/windows-hardware/customize/desktop/unattend/microsoft-windows-tcpip-interfaces-interface-ipv4settings).

```
<component name="Microsoft-Windows-TCPIP" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
   <Interfaces>
            <Interface wcm:action="add">
               <Ipv4Settings>
                  <DhcpEnabled>false</DhcpEnabled>
               </Ipv4Settings>
               <Ipv6Settings>
                  <DhcpEnabled>false</DhcpEnabled>
               </Ipv6Settings>
               <Identifier>Ethernet0</Identifier>
               <UnicastIpAddresses>
                  <IpAddress wcm:action="add" wcm:keyValue="1"><!--REPLACE WITH IPCIDR--></IpAddress>
               </UnicastIpAddresses>
               <Routes>
                  <Route wcm:action="add">
                     <Identifier>1</Identifier>
                     <Prefix>0.0.0.0/0</Prefix>
                     <NextHopAddress><!--REPLACE WITH GATEWAY--></NextHopAddress>
                  </Route>
               </Routes>
            </Interface>
         </Interfaces>
      </component>
</component>
```

We will consider testing this and including in the configuration if it proves workable.

Thanks, 
Ryan

**Comment by tenthirtyam** [comment]
This can be addressed by modifying the config files per https://github.com/rainpole/packer-vsphere/issues/17#issuecomment-883461995.
