### ISSUE TITLE
Network disconnected in Ubuntu

### ISSUE THREAD

**Issue by alexanderek** [rainpole/packer-vsphere#20]
**Description**

After creating a virtual machine from the Ubuntu 20.04 template. The network adapter in the cloned virtual machine is in the disconnected status. (There is no network assigned to this virtual machine.)

**Steps to Reproduce**
Create a template with Ubuntu 20.04.
Create VM from Template.

**VMware vSphere Version**
7.0.2

**HashiCorp Packer Version**
Packer version: 1.7.3 [go1.16.5 darwin amd64]

**Guest Operating System and Environment Details**
MacOS 11.4

**Guest Operating System**
Ubuntu Server 20.04.2 LTS

**Comment by tenthirtyam** [comment]
This is a known issue. I'll update the README with some Known Issues and mark this for further investigation. If you have a suggested fix or discover one, please leave a comment.

For background, the repository was originally designed to be use with vRealize Automation 8 / Cloud which addresses the NIC during the guest customization process.

Ryan

**Comment by tenthirtyam** [comment]
The network interface for Linux machine images are in a disconnected after conversion to template / OVF.  This does not effect Windows images.

**Workaround**: Manually or programmatically connect the network interface post-provisioning.

**Cause:** The cause appears to be present in shell script initialized by the provisioner before the shutdown. We will need to modify the script for each distro to account for the issue.

**Comment by alexanderek** [comment]
Interestingly, this issue did not occur with rhel and centos. I've tested this.

**Comment by tenthirtyam** [comment]
It's likely related to cloud-init in Ubuntu 20.04.

**Comment by alexanderek** [comment]
I think I found the [answer](https://githubmemory.com/repo/vmware/open-vm-tools/issues/508), but for some reason it didn't work. :(
`echo 'datasource_list: [ "DataSourceOVF" ]' > /etc/cloud/cloud.cfg.d/99-DataSourceOVF.cfg`

**Comment by tenthirtyam** [comment]
@alexanderek - with some patience the machine image does connect the NIC - this is a known issue that impacts some systemd based machine images.

I've updated the script for to use `vgauth.service` instead of `vgauthd.service` as the `After=dbus.service` line was not being added to `open-vm-tools.service`. The former is used in Ubuntu while the latter is used in RHEL-based guestOS.

If waiting for the customization to run does not work for you, you can consider adding a line near the end of the script to remove cloud-init.

`sudo apt-get purge cloud-init`.

Ryan

**Comment by tenthirtyam** [comment]
> I think I found the [answer](https://githubmemory.com/repo/vmware/open-vm-tools/issues/508), but for some reason it didn't work. :(
> `echo 'datasource_list: [ "DataSourceOVF" ]' > /etc/cloud/cloud.cfg.d/99-DataSourceOVF.cfg`

I'll take a look at this one, too. It may come in useful for Issue https://github.com/rainpole/packer-vsphere/issues/5.

Ryan

**Comment by alexanderek** [comment]
@tenthirtyam 
I removed the cloud-init completely, and that solved the issue. Thanks.

`sudo apt purge cloud-init -y
;sudo apt autoremove -y
;sudo rm -rf /etc/cloud`

**Comment by tenthirtyam** [comment]
Good to hear!

**Comment by it-pappa** [comment]
@alexanderek Hi,

I have the same issue, but have tryed the purge option in a script in the provisioning portion of packer but didnt help, and machine just dont turn of and converts.

**Comment by it-pappa** [comment]
@tenthirtyam  oh sorry. I thought this was the hashicorp packer-vsphere repo. Sorry,,, long day. 

But are experincing the same issue.

**Comment by tenthirtyam** [comment]
@it-pappa - take a look at the examples in this repo for Ubuntu. These should help you get a good working configuration.

Ryan
