### ISSUE TITLE
Linux and UEFI

### ISSUE THREAD

**Issue by jbpoint** [rainpole/packer-vsphere#21]
Hi,

I tried to install Almalinux and Ubuntu with the KS config with efi, but i dont get it to work.
Any suggestions?

**Comment by tenthirtyam** [comment]
If if recall correctly, only specific GuestOS supported UEFI. During my testing I was able to get it to work with RHEL 8 (and Windows, too) but ai've not looked at it further after the issue with cloning was resolved in vSphere 7.0 Update 2.

We can plan to test this a little further and update the README accordingly.

Ryan

**Comment by jbpoint** [comment]
Windows works like charm - 2016 and 2019.
But i didnt get it to work with Ubuntu nor Almalinux. :/ 

Thank you :)

**Comment by tenthirtyam** [comment]
UEFI is not a recommend Firmware option for Ubuntu 64-bit in vSphere 7.0 Update 2. You can see this when creating a VM manually under VM Options. I've found that it will fail to boot if created manually with UEFI.

That said, it _should_ work for RHEL (with the RHEL8 option as it's recommended for the default), and for CentOS, Alma, and Rocky (using the CentOS8 type) but I've not tested the latter (yet).

Ryan

**Comment by tenthirtyam** [comment]
I recall that the issue for UEFI with RHEL-based that extra argument is needed in the boot sequence just like is needed for RHEL 8 with UEFI.

You'll need to edit the boot_command to add `<wait><leftCtrlOn>x<leftCtrlOff><wait><enter>`

 `boot_command             = ["<tab>","text ks=http://{{ .HTTPIP }}:{{ .HTTPPort }}/${var.http_file}","<enter><wait><leftCtrlOn>x<leftCtrlOff><wait><enter>"]`

My initial test today, whilst I have time, shows that it will continue but will pause just past at the selection of language. I'll look at this a little further when time permits.

Ryan

**Comment by tenthirtyam** [comment]
Please note, we plan to update all guestOS types for machine images in this repository to use only their "(Recommended)" firmware settings based on vSphere version support in this repository per https://github.com/rainpole/packer-vsphere/issues/22 now that vSphere 7.0 Update 2 has resolved the content library OVF issue. Commit [260dbfc](https://github.com/rainpole/packer-vsphere/commit/260dbfc46c6a7d15bd47f19fa801ff4ec6e4a0d4) is a precursor to this change.

**Comment by jbpoint** [comment]
My initial test today, whilst I have time, shows that it will continue but will pause just past at the selection of language. I'll look at this a little further when time permits.

Did you solve this issue? Because i am facing the same problem

**Comment by tenthirtyam** [comment]
Yes, use:

 ```
boot_command = ["up","e","<down><down><end><wait>"," text ks=http://{{ .HTTPIP }}:{{ .HTTPPort }}/${var.http_file}","<enter><wait><leftCtrlOn>x<leftCtrlOff>"]
```

The README has been updated.

**Comment by jbpoint** [comment]
Still leads to ...

![image](https://user-images.githubusercontent.com/87362739/126743875-610cee23-3d7f-445e-83f1-d4d360084fb4.png)

**Comment by tenthirtyam** [comment]
Please paste or giat your template and variables files. I'v confirmed efi-secure worked with the updated boot command which also does not launch the UI installer.

Ryan
