### ISSUE TITLE
2 errors at the end of build

### ISSUE THREAD

**Issue by akatukiyou** [rainpole/packer-vsphere#29]
Packer 1.7.4
Vsphere: 7.0.2

Build successfully, but at the end of the build, there were two errors, just wondering what the messages mean?

`==> vsphere-iso.linux-<sensitive>-server: Importing VM OVF template linux-<sensitive>-server-20-04-lts to Content Library...
==> vsphere-iso.linux-<sensitive>-server: Destroying VM...
==> vsphere-iso.linux-<sensitive>-server: Running post-processor:  (type manifest)
Build 'vsphere-iso.linux-<sensitive>-server' errored after 8 minutes 12 seconds: 2 error(s) occurred:

* Post-processor failed: Unable to write ../../../manifests/2021-09-03 00:24 UTC-linux-<sensitive>-server-20-04-lts.json: open ../../../manifests/2021-09-03 00:24 UTC-linux-<sensitive>-server-20-04-lts.json: The system cannot find the path specified.
* Error destroying builder artifact: reading body msgpack decode error [pos 992]: reflect.Set: value of type map[interface {}]interface {} is not assignable to type error; bad artifact: []string(nil)

==> Wait completed after 8 minutes 12 seconds

==> Some builds didn't complete successfully and had errors:
--> vsphere-iso.linux-<sensitive>-server: 2 error(s) occurred:

* Post-processor failed: Unable to write ../../../manifests/2021-09-03 00:24 UTC-linux-<sensitive>-server-20-04-lts.json: open ../../../manifests/2021-09-03 00:24 UTC-linux-<sensitive>-server-20-04-lts.json: The system cannot find the path specified.
* Error destroying builder artifact: reading body msgpack decode error [pos 992]: reflect.Set: value of type map[interface {}]interface {} is not assignable to type error; bad artifact: []string(nil)

==> Builds finished but no artifacts were created.
Done.
`

**Comment by tenthirtyam** [comment]
It looks as though the manifest post-processor is not able to save to a `manifests` folder that should be w/in the `packer-vsphere` directory. It does however look like the machine image was created and copied to the desired content library.

`The system cannot find the path specified.`

```
packer-vsphere/ 
├── build.sh
├── README.md
├── builds
├── certificates
├── configs
├── manifests        <<<<--------- `The system cannot find the path specified.`
├── scripts
```

The `manifests` directory contains the manifest created after the completion of each build.

Ryan

[GitHub Discussions](https://github.com/rainpole/packer-vsphere/discussions.) can be used in the future.
