### ISSUE TITLE
[BUG] Missing "manifest" directory after git clone

### ISSUE THREAD

**Issue by necarnot** [rainpole/packer-vsphere#36]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### VMware vSphere

7.0 Update 2

### HashiCorp Packer

1.7.4

### HashiCorp Packer Plugin for VMware vSphere

1.0.1

### Guest Operating System

CentOS 8.4

### Description

Hello, and thank you for this wonderful work.

Nothing serious, but when git cloning this repo, the manifest directory is missing at the root level (probably because git does not allow empty dirs).
Maybe you could add a ".placehoder" file in the manifest dir and commit it?

### Expected Behavior

A packer run should be able to write its manifest in the end.

### Actual Behavior

Missing manifest dir leads to everything working fine (the template is generated), but as the manifest can not be written, the whole operation appears as a failure, and the template is cleaned (too bad).

### Steps to Reproduce

Just clone the repo, adjust according to the README, launch it, and witness the sad end.

### Log Fragments and Files

[...]
Build 'vsphere-iso.linux-ubuntu-server' errored after 5 minutes 40 seconds: 1 error(s) occurred:

* Post-processor failed: Unable to write ../../../manifests/2021-09-15 13:43 UTC-linux-ubuntu-server-20-04-lts.json: open ../../../manifests/2021-09-15 13:43 UTC-linux-ubuntu-server-20-04-lts.json: no such file or directory

**Comment by tenthirtyam** [comment]
Resolved: https://github.com/rainpole/packer-vsphere/pull/37

This will be removed in an upcoming update. 😉

**Comment by tenthirtyam** [comment]
Refactored in https://github.com/rainpole/packer-vsphere/pull/38.
