### ISSUE TITLE
[ENHANCEMENT] Add option to bind IP address for Packer HTTP server with Linux builds

### ISSUE THREAD

**Issue by gcblack** [rainpole/packer-vsphere#49]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### Description

Currently, when the build starts, the boot command references the {{ .HTTPIP }} variable, which Packers sets as what ever the IP of the first interface is.
Adding this variable allows you to specify which IP address the build will use to get it's kickstart file from.

### Use Case(s)

Packer build servers that service multiple separate networks or just have multiple interfaces.

### Potential Configuration

1.	Create a new variable in ‘builds > linux > centos-linux-8 > variables.pkr.hcl file: 
               variable "common_http_bind_address" {
               type        = string
               description = "Force build to use this IP to download the kickstart file."
               }

2. Define the variable in ‘builds > common.pkvars.hcl’ file under the “Boot and Provisioning Settings” '
               common_http_bind_address = "192.2.0.201"

3. Modify the "boot_command" in the 'builds > linux > centos-linux-8 > linux-centos-linux.pkr.hcl’ to use the new variable
               `boot_command     = ["up", "e", "<down><down><end><wait>", "text inst.ks=http://${var.common_http_bind_address}:{{ .HTTPPort }}/ks.cfg", "<enter><wait><leftCtrlOn>x<leftCtrlOff>"]`

### References

This could be used for all builds that require the ks file to be retrieved from the http server.

**Comment by tenthirtyam** [comment]
Thanks, @gcblack. I'll add this enhancement.

Ryan

**Comment by sestegra** [comment]
Use `http_ip` parameter instead
> `http_ip` (string) - The IP address to use for the HTTP server started to serve the `http_directory`. If unset, Packer will automatically discover and assign an IP.

**Comment by tenthirtyam** [comment]
> Use `http_ip` parameter instead
> 
> > `http_ip` (string) - The IP address to use for the HTTP server started to serve the `http_directory`. If unset, Packer will automatically discover and assign an IP.

That's indeed the change I'm making. :)

Ryan
