### ISSUE TITLE
Photon OS 3.0 builds fail due to incorrect package repo

### ISSUE THREAD

**Issue by lamw** [rainpole/packer-vsphere#6]
When filing a bug, please include the following information. 

**Description**

VMware recently [migrated Photon OS to a new package repository](https://blogs.vmware.com/vsphere/2020/10/photon-os-announces-migration-to-new-package-repository.html) and for existing 3.x ISO images, users must point to the new repo which is now located at packages.vmware.com (previously hosted on bintray)

**Expected Behavior**

Successfully complete `tdnf -y update` along installing any other packages

**Actual Behavior**

Failed to retrieve updates as the package repository is incorrect

```
==> vsphere-iso.linux-photon-server: Error: 401 when downloading https://dl.bintray.com/vmware/photon_release_3.0_x86_64/repodata/repomd.xml
==> vsphere-iso.linux-photon-server: . Please check repo url.
==> vsphere-iso.linux-photon-server: Error: Failed to synchronize cache for repo 'VMware Photon Linux 3.0(x86_64)' from 'https://dl.bintray.com/vmware/photon_release_3.0_x86_64'
==> vsphere-iso.linux-photon-server: Error: 401 when downloading https://dl.bintray.com/vmware/photon_updates_3.0_x86_64/repodata/repomd.xml
==> vsphere-iso.linux-photon-server: . Please check repo url.
==> vsphere-iso.linux-photon-server: Error: Failed to synchronize cache for repo 'VMware Photon Linux 3.0(x86_64) Updates' from 'https://dl.bintray.com/vmware/photon_updates_3.0_x86_64'
==> vsphere-iso.linux-photon-server: Error: 401 when downloading https://dl.bintray.com/vmware/photon_extras_3.0_x86_64/repodata/repomd.xml
==> vsphere-iso.linux-photon-server: . Please check repo url.
==> vsphere-iso.linux-photon-server: Error: Failed to synchronize cache for repo 'VMware Photon Extras 3.0(x86_64)' from 'https://dl.bintray.com/vmware/photon_extras_3.0_x86_64'
==> vsphere-iso.linux-photon-server: Error(1011) : No matching packages
```

**Steps to Reproduce**

Run the default `VMware Photon OS 3` build

**VMware vSphere Version**

`vSphere 7.0 Update 1 Build 16858589 `

**HashiCorp Packer Version**

`1.6.5`

**Simplified Packer Build or Variables File(s)**

N/A

**Guest Operating System and Environment Details**

`Photon OS 3.0 Rev 2 - photon-3.0-a0f216d.iso`

https://packages.vmware.com/photon/3.0/Rev2/iso/Update2/photon-3.0-a0f216d.iso

**Guest Operating System**

N/A

**Log Fragments and crash.log Files**

N/A

**Additional Context**

N/A

**Comment by tenthirtyam** [comment]
Resolved in https://github.com/rainpole/packer-vsphere/pull/7. Thank you, @lamw. 👍🏻
