### ISSUE TITLE
[ENHANCEMENT] Remove `rm -f output-vmware-iso/*.ova` from `build.sh`

### ISSUE THREAD

**Issue by sestegra** [rainpole/packer-vsphere#68]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### Description

I don't get what `rm -f output-vmware-iso/*.ova` is for.

### Use Case(s)

N/A

### Potential Configuration

N/A

**Comment by tenthirtyam** [comment]
It's a remnant from when I was first working on the repo. :)
