### ISSUE TITLE
[BUG] Possible IP address collision on the DHCP/DNS server when building all Windows images at the same time

### ISSUE THREAD

**Issue by sestegra** [rainpole/packer-vsphere#90]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### VMware vSphere

7.0 Update 2

### HashiCorp Packer

1.7.6

### HashiCorp Packer Plugin for VMware vSphere

1.0.1

### Guest Operating System

macOS Big Sur (Intel)

### Description

When building multiple images from the same configuration (i.e. `windows-server-*`) at the same time, the DHCP server receives the same hostname for each created VM.

### Expected Behavior

Packer could create the VMs with different names.

### Actual Behavior

Packer creates the VMs with the same name.

### Steps to Reproduce

- Launch `build.sh` script
- Select `Windows Server * - All` option

**Comment by tenthirtyam** [comment]
Interesting. I've never seen this occur in my testbeds.

Ryan

**Comment by tenthirtyam** [comment]
I'll make an adjustment to build with a unique >15 char name based on the build. I don't believe there is a Packer function to generate a random string - only uuid/s.

Ryan

**Comment by tenthirtyam** [comment]
I think I have an elegant solution for the problem and will include in an update I'm finishing up for 21.10.

Ryan
